### ISSUE TITLE
Using with laravel and vue

### ISSUE THREAD

**Issue by zaxaco** [JohnPremKumar/vite-plugin-favicons-inject#16]
I tried to use this code in a  laravel+inertia+vue project.

my vit.config.js (in root folder) : 
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

import vitePluginFaviconsInject from 'vite-plugin-favicons-inject';

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.js',
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        vitePluginFaviconsInject('resources/img/logo/rosesefid.png'),
    ],
});
```

that facing the following error : 

```
error during build:
Error: NO_FILES_FOUND
    at Object.closeBundle (C:\laragon2\www\alomoshaver\node_modules\vite-plugin-favicons-inject\dist\cjs\index.js:94:15)
    at file:///C:/laragon2/www/alomoshaver/node_modules/rollup/dist/es/shared/node-entry.js:24343:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///C:/laragon2/www/alomoshaver/node_modules/rollup/dist/es/shared/node-entry.js:24271:9)
    at async Object.close (file:///C:/laragon2/www/alomoshaver/node_modules/rollup/dist/es/shared/node-entry.js:25573:13)
    at async build (file:///C:/laragon2/www/alomoshaver/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44680:13)
    at async CAC.<anonymous> (file:///C:/laragon2/www/alomoshaver/node_modules/vite/dist/node/cli.js:813:9)
```

What should be the path of the logo?

**Comment by Yannik** [comment]
Same issue here. Any ideas how to solve this @JohnPremKumar ?

**Comment by davideprevosto** [comment]
@Yannik have you found any workaround? I have the same issue.

**Comment by Yannik** [comment]
@davideprevosto I ended up using https://www.npmjs.com/package/vite-plugin-favicon which requires
```
  "overrides": {
        "vite-plugin-favicon": {
            "favicons": "^7.1.0"
        }
    }
``` 
but otherwise works fine.
